"""add-client-contact

Revision ID: 0bfdb54d0aad
Revises: 365b22276210
Create Date: 2025-10-11 15:49:13.722136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0bfdb54d0aad"
down_revision: Union[str, Sequence[str], None] = "365b22276210"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipment", sa.Column("client_contact_email", sa.String(), nullable=True)
    )
    op.add_column(
        "shipment", sa.Column("client_contact_phone", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipment", "client_contact_phone")
    op.drop_column("shipment", "client_contact_email")
    # ### end Alembic commands ###
