"""make seller email unique

Revision ID: 365b22276210
Revises: e6571efb8b21
Create Date: 2025-10-07 15:28:09.926632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365b22276210'
down_revision: Union[str, Sequence[str], None] = 'e6571efb8b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_seller_email'), 'seller', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_email'), table_name='seller')
    # ### end Alembic commands ###
