"""add-delivery-partner-table

Revision ID: 37b13c625b1c
Revises:
Create Date: 2025-10-05 14:24:40.548985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "37b13c625b1c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_partner",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("serviceable_zip_codes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("max_handling_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seller",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("content", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("destination", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "placed",
                "out_for_delivery",
                "in_transit",
                "delivered",
                name="shipmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("estimated_delivery", sa.DateTime(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_partner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_partner_id"],
            ["delivery_partner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment")
    op.drop_table("seller")
    op.drop_table("delivery_partner")
    # ### end Alembic commands ###
